CREATE DATABASE libreria;

USE libreria;

CREATE TABLE USUARIOS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  contraseña VARCHAR(255) NOT NULL,
  dirección VARCHAR(255) NOT NULL,
  teléfono VARCHAR(20) NOT NULL
);

CREATE TABLE LIBROS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  título VARCHAR(255) NOT NULL,
  autor VARCHAR(255) NOT NULL,
  precio DECIMAL(10, 2) NOT NULL,
  cantidad_en_inventario INT NOT NULL
);

CREATE TABLE CARRITO (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_usuario INT NOT NULL,
  ID_libro INT NOT NULL,
  cantidad INT NOT NULL,
  monto_total DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (ID_usuario) REFERENCES USUARIOS(ID),
  FOREIGN KEY (ID_libro) REFERENCES LIBROS(ID)
);